# Generated by Django 5.1.1 on 2024-09-08 15:32

import datetime
import queue
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='band',
            name='biography',
            field=models.CharField(default=queue.Full, max_length=100),
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(default=queue.Full, max_length=100),
        ),
        migrations.AddField(
            model_name='band',
            name='official_homepage',
            field=models.URLField(default=queue.Full),
        ),
        migrations.AddField(
            model_name='band',
            name='year_formed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
